### ISSUE TITLE
how to add an constrained tetrahedron factor to revise this project

### ISSUE THREAD

**Issue by cherydeng** [PANFACTORY/Delaunay3Dver3#3]

**Comment by PANFACTORY** [comment]
@Dengrui-mihoyo 
Thanks to have an interest to this project, and sorry for the late reply.

Am I correct in understanding that constrained tetrahedron factors are for example aspect ratio, max/min angle, sum of edge length and so on?

If so, you have to implement processes adding nodes in the mesh to satisfy them.
Please add these processes in the function `MakeFineMesh` in  `src/cpp/Delaunay.h`.
(At present it finds elements having longest edge and splits them.)
If you have implementation ideas, please create pull requests.

Forgive me if I make you feel bad by using incorrect words in English, I don't mean it at all.

**Comment by cherydeng** [comment]
Thanks for your reply, Sorry for my expression,  I simply wanted to know how to write the CDT in 3D space. Please don't pay attention to English expressions, If you have any ideas, please contact me.

**Comment by PANFACTORY** [comment]
Of course.
Thank you for your cooperation.
